/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uasramdhe;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Dtmhs extends javax.swing.JFrame {
    private void kosongkan(){
     name.setEditable(true);
     name.setText(null);
     id.setText(null);
     cls.setText(null);
     alt.setText(null);
     klm.setSelectedItem(this);
     alt.setText(null);
     agm.setSelectedItem(this);
     
    }
    
    private DefaultTableModel model;
private String SQL;   

  
private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Nama Mahasiswa");
        model.addColumn("NIM");
        model.addColumn("Kelas");
        model.addColumn("Jurusan");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Agama");
        
        try{
            int no = 1;
            String sql = "SELECT * FROM dtmhs";
            java.sql.Connection conn= (Connection)Konfig.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1), res.getString(2), res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
            
            tbl.setModel(model);
            
        }catch (Exception e){
            System.out.println("Error!" + e.getMessage());
        }
    }

    /**
     * Creates new form Dtmhs
     */
    public Dtmhs() {
        initComponents();
        
        tampilkan_data();
        kosongkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        agm = new javax.swing.JComboBox();
        klm = new javax.swing.JComboBox();
        cls = new javax.swing.JTextField();
        sv = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        edt = new javax.swing.JButton();
        prd = new javax.swing.JTextField();
        dell = new javax.swing.JButton();
        ext = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Aplikasi Manajemen Data Mahasiswa");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 0, 370, 60);

        jLabel2.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Silahkan Isi Data di kolom yang Tersedia.");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(30, 40, 290, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kelamin :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 260, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 100, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NIM :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 130, 70, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(50, 290, 100, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agama:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 330, 60, 15);
        jPanel2.add(alt);
        alt.setBounds(110, 300, 490, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jurusan:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(30, 220, 60, 15);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kelas :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 170, 60, 20);
        jPanel2.add(id);
        id.setBounds(80, 130, 240, 30);

        agm.setBackground(new java.awt.Color(51, 0, 255));
        agm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Ateis", "Animisme", "Budha", "Dinamisme", "Hindu", "Islam", "Kejawen", "Kristen Katholik", "Kristen Protestan", "Konghucu" }));
        jPanel2.add(agm);
        agm.setBounds(110, 330, 180, 30);

        klm.setBackground(new java.awt.Color(0, 51, 255));
        klm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Pria", "Wanita" }));
        jPanel2.add(klm);
        klm.setBounds(120, 260, 180, 30);
        jPanel2.add(cls);
        cls.setBounds(80, 170, 240, 30);

        sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/save.png"))); // NOI18N
        sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svActionPerformed(evt);
            }
        });
        jPanel2.add(sv);
        sv.setBounds(610, 290, 50, 50);
        jPanel2.add(name);
        name.setBounds(90, 90, 210, 30);

        edt.setText("Edit");
        edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtActionPerformed(evt);
            }
        });
        jPanel2.add(edt);
        edt.setBounds(120, 370, 73, 23);
        jPanel2.add(prd);
        prd.setBounds(90, 210, 240, 30);

        dell.setBackground(new java.awt.Color(0, 204, 255));
        dell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/dell.png"))); // NOI18N
        dell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellActionPerformed(evt);
            }
        });
        jPanel2.add(dell);
        dell.setBounds(670, 290, 40, 50);

        ext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/ext.png"))); // NOI18N
        ext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extActionPerformed(evt);
            }
        });
        jPanel2.add(ext);
        ext.setBounds(950, 20, 80, 80);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 360, 90, 90);

        reset.setBackground(new java.awt.Color(0, 102, 204));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/reset.png"))); // NOI18N
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(330, 80, 50, 50);

        tbl.setBackground(new java.awt.Color(255, 153, 0));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 460, 1020, 1580);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasramdhe/WhatsApp Image 2021-07-11 at 20.27.23.jpeg"))); // NOI18N
        jPanel2.add(bg);
        bg.setBounds(0, -150, 1300, 1210);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 2040));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
        
      
    
    private void svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO dtmhs VALUES('"+name.getText()+"','"+id.getText()+"','"+cls.getText()+"','"+prd.getText()+"','"+klm.getSelectedItem()+"','"+alt.getText()+"','"+agm.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
            tampilkan_data();
            kosongkan();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
       
        
    
    }//GEN-LAST:event_svActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
        int baris = tbl.rowAtPoint(evt.getPoint());
        String nama =tbl.getValueAt(baris, 1).toString();
        name.setText(nama);
        String nim = tbl.getValueAt(baris,2).toString();
        id.setText(nim);
        String kelas = tbl.getValueAt(baris, 3).toString();
        cls.setText(kelas);
        String prodi = tbl.getValueAt(baris, 4).toString();
        prd.setText(prodi);
        String gender = tbl.getValueAt(baris, 5).toString();
        klm.setSelectedItem(gender);
        String alamat = tbl.getValueAt(baris, 6).toString();
        alt.setText(alamat);
        String agama = tbl.getValueAt(baris, 7).toString();
        agm.setSelectedItem(agama);
    }//GEN-LAST:event_tblMouseClicked

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_resetActionPerformed

    private void edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Update dtmhs set nama='"+name.getText()+"',nim='"+id.getText()+"',kelas='"+cls.getText()+"',prodi='"+prd.getText()+"',gender='"+klm.getSelectedItem()+"',alamat='"+"',agama='"+agm.getSelectedItem()+"'WHERE nama ='"+name.getText()+"'";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Telah Berhasil Dilakukan");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Di Edit"+e.getMessage());
        }
        tampilkan_data();
        kosongkan();
    }//GEN-LAST:event_edtActionPerformed

    private void dellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellActionPerformed
        // TODO add your handling code here:
         try{
        String sql = "DELETE FROM dtmhs WHERE nama='"+name.getText()+"'";
        java.sql.Connection conn = (Connection)Konfig.configDB();
        java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
        pstm.execute();
        JOptionPane.showMessageDialog(null, "Data Terhapus");
    }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, "Data Gagal Di Hapus"+e.getMessage());
    }
        tampilkan_data();
        kosongkan();
    }//GEN-LAST:event_dellActionPerformed

    private void extActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_extActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dtmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dtmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dtmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dtmhs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dtmhs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox agm;
    private javax.swing.JTextField alt;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cls;
    private javax.swing.JButton dell;
    private javax.swing.JButton edt;
    private javax.swing.JButton ext;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox klm;
    private javax.swing.JTextField name;
    private javax.swing.JTextField prd;
    private javax.swing.JButton reset;
    private javax.swing.JButton sv;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

     };
